name: totallymakescents
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib >= 3.8
  - pandas >= 2.0
  - pip >= 24.0
  - python = 3.12
  - scikit-learn >= 1.4
  - numpy = 1.26.4
  - geckodriver
  - pip:
    - st-files-connection
    - gcsfs
    - beautifulsoup4
    - selenium
    - selenium-stealth
    - splinter
    - webdriver-manager
    - torch
    - torchvision
    - plotly
    - streamlit-extras