name: totallymakescents
channels:
  - conda-forge
dependencies:
  - matplotlib >= 3.8
  - pandas >= 2.0
  - pip >= 24.0
  - python = 3.12
  - scikit-learn >= 1.4
  - numpy = 1.26.4
  - gcsfs = 2025.7.0
  - st-files-connection